# Generated by Django 5.1.1 on 2025-03-04 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0004_remove_room_hotel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
